# JDK 9 build via https://github.com/reactive-streams/reactive-streams-jvm/pull/296/files 

sudo: required
language: scala
scala:
   - 2.12.2
   
script: 
  - sbt '; publishLocal; scripted'
  - cd plugin-tester
  - sbt -Dproject.version=$(cat ../version.sbt | awk '{print $5}' | sed 's/"//g') test 

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

dist: trusty
#group: edge

matrix:
  include:
#    - jdk: oraclejdk8 # should then NOT compile any of the JDK 9 stuff
    - jdk: oraclejdk9

env:
  global:
  - TERM=dumb
  - DEFAULT_TIMEOUT_MILLIS=300
  - DEFAULT_NO_SIGNALS_TIMEOUT_MILLIS=200
  - PUBLISHER_REFERENCE_GC_TIMEOUT_MILLIS=300
addons: # Fix OpenJDK build. Issue: https://github.com/travis-ci/travis-ci/issues/5227 & https://docs.travis-ci.com/user/hostname
  ostname: mr-jar
